alliance-genome/agr_curation

.github/workflows/github-production-release.yml
Added code to Github actions to send notification to Slack on successfull deployment.
=> Added deployment notifications

src/test/java/org/alliancegenome/curation_api/bulkupload/GeneBulkUploadITCase.java, src/test/resources/gene/01_all_fields.json
How to test:
`make api integration-test`
=> SCRUM-248: add test for file 01_all_fields

src/test/resources/crud/disease_annotation/01_valid_gene_subject_id.json, src/test/resources/crud/disease_annotation/02_valid_allele_subject_id.json, src/test/resources/crud/disease_annotation/03_valid_agm_subject_id.json, src/test/resources/crud/disease_annotation/04_invalid_subject_id.json, src/test/resources/crud/disease_annotation/05_empty_subject_id.json, src/test/resources/crud/disease_annotation/06_missing_subject.json, src/test/resources/crud/disease_annotation/07_invalid_object_id.json, src/test/resources/crud/disease_annotation/08_empty_object_id.json, src/test/resources/crud/disease_annotation/09_missing_object.json
Previous CRUD test files updated to include object, diseaseRelation, and referenceList as these will presumable be required fields in the future.  New test files added for missing subject, empty subject ID, invalid object ID, missing object, and empty object ID.
=> Scrum 496 test file updates

src/main/java/org/alliancegenome/curation_api/base/BaseCrudRESTInterface.java, src/main/java/org/alliancegenome/curation_api/crud/controllers/MoleculeController.java, src/main/java/org/alliancegenome/curation_api/interfaces/rest/MoleculeRESTInterface.java, src/main/java/org/alliancegenome/curation_api/services/MoleculeService.java, src/test/java/org/alliancegenome/curation_api/bulkupload/MoleculeBulkUploadITCase.java, src/test/resources/bulk/05_molecule/00_mod_examples.json, src/test/resources/bulk/05_molecule/01_all_fields.json, src/test/resources/bulk/05_molecule/02_no_id.json, src/test/resources/bulk/05_molecule/03_no_name.json, src/test/resources/bulk/05_molecule/04_no_inchi.json, src/test/resources/bulk/05_molecule/05_no_inchikey.json, src/test/resources/bulk/05_molecule/06_no_iupac.json, src/test/resources/bulk/05_molecule/07_no_formula.json, src/test/resources/bulk/05_molecule/08_no_smiles.json, src/test/resources/bulk/05_molecule/09_no_synonyms.json, src/test/resources/bulk/05_molecule/10_no_cross_references.json
Added logic to molecule service to skip entries with no/empty name field.
Integration tests for molecules added and passing.
=> Molecule constraints and testing

src/main/cliapp/src/App.js, src/main/cliapp/src/components/Dashboard.js, src/main/cliapp/src/components/MoleculesComponent.js, src/main/cliapp/src/service/MoleculeService.js, src/main/java/org/alliancegenome/curation_api/model/entities/Molecule.java
Added table and dashboard summary for molecules.
=> SCRUM-862 molecule table

src/main/cliapp/src/components/DiseaseAnnotationsComponent.js, src/main/java/org/alliancegenome/curation_api/model/entities/DiseaseAnnotation.java
Added (currently non-editable) 'with' column to disease annotation table.
=> Add with column

src/main/cliapp/src/components/DiseaseAnnotationsComponent.js
Changed column order to match mockups.
Fixed filtering of 'with' column and results counts.
=> SCRUM-866 'with' position, sorting, filtering

src/main/cliapp/src/App.js, src/main/cliapp/src/components/Dashboard.js, src/main/cliapp/src/components/ontologies/DAOOntologyComponent.js, src/main/cliapp/src/components/ontologies/EMAPAOntologyComponent.js, src/main/cliapp/src/components/ontologies/WBbtOntologyComponent.js, src/main/java/org/alliancegenome/curation_api/controllers/bulk/ontology/DaoTermBulkController.java, src/main/java/org/alliancegenome/curation_api/controllers/bulk/ontology/EmapaTermBulkController.java, src/main/java/org/alliancegenome/curation_api/controllers/bulk/ontology/WbbtTermBulkController.java, src/main/java/org/alliancegenome/curation_api/controllers/crud/ontology/DaoTermController.java, src/main/java/org/alliancegenome/curation_api/controllers/crud/ontology/EmapaTermController.java, src/main/java/org/alliancegenome/curation_api/controllers/crud/ontology/WbbtTermController.java, src/main/java/org/alliancegenome/curation_api/dao/ontology/DaoTermDAO.java, src/main/java/org/alliancegenome/curation_api/dao/ontology/EmapaTermDAO.java, src/main/java/org/alliancegenome/curation_api/dao/ontology/WbbtTermDAO.java, src/main/java/org/alliancegenome/curation_api/interfaces/bulk/ontology/DaoTermBulkRESTInterface.java, src/main/java/org/alliancegenome/curation_api/interfaces/bulk/ontology/EmapaTermBulkRESTInterface.java, src/main/java/org/alliancegenome/curation_api/interfaces/bulk/ontology/WbbtTermBulkRESTInterface.java, src/main/java/org/alliancegenome/curation_api/interfaces/crud/ontology/DaoTermRESTInterface.java, src/main/java/org/alliancegenome/curation_api/interfaces/crud/ontology/EmapaTermRESTInterface.java, src/main/java/org/alliancegenome/curation_api/interfaces/crud/ontology/WbbtTermRESTInterface.java, src/main/java/org/alliancegenome/curation_api/model/entities/ontology/DAOTerm.java, src/main/java/org/alliancegenome/curation_api/model/entities/ontology/EMAPATerm.java, src/main/java/org/alliancegenome/curation_api/model/entities/ontology/WBbtTerm.java, src/main/java/org/alliancegenome/curation_api/services/ontology/DaoTermService.java, src/main/java/org/alliancegenome/curation_api/services/ontology/EmapaTermService.java, src/main/java/org/alliancegenome/curation_api/services/ontology/WbbtTermService.java
EMAPA currently hidden from UI as format of OWL file appears to be incorrect.
=> SCRUM-873; SCRUM-887; SCRUM-892 loading DAO, EMAPA, and WBbt ontologies

src/main/cliapp/src/components/WithEditor.js, src/main/cliapp/src/components/datatables/DiseaseAnnotationsComponent.js
Implement editing of 'with' attribute (refactored from previous PR).
Allow selection of multiple HGNC genes.
Only include HGNC genes in autocomplete.
=> SCRUM-908 Edit disease annotation 'with' mk2

src/main/cliapp/src/App.js, src/main/cliapp/src/components/Dashboard.js, src/main/java/org/alliancegenome/curation_api/base/BaseOntologyTermBulkController.java, src/main/java/org/alliancegenome/curation_api/controllers/bulk/ontology/DaoTermBulkController.java, src/main/java/org/alliancegenome/curation_api/controllers/bulk/ontology/EmapaTermBulkController.java, src/main/java/org/alliancegenome/curation_api/controllers/bulk/ontology/ZecoTermBulkController.java, src/main/java/org/alliancegenome/curation_api/services/helpers/GenericOntologyLoadConfig.java, src/main/java/org/alliancegenome/curation_api/services/helpers/GenericOntologyLoadHelper.java
@oblodgett - required a slight change in the logic of which nodes to let through, but otherwise unchanged from the code you pushed with the exception of unhiding the EMAPA ontology table from the UI.
Tested on DO, DAO, WBbt, and EMAPA ontologies.
=> SCRUM-887 and SCRUM-892

src/main/cliapp/src/App.js, src/main/cliapp/src/components/Dashboard.js, src/main/cliapp/src/components/ontologies/ZECOOntologyComponent.js, src/main/java/org/alliancegenome/curation_api/services/helpers/GenericOntologyLoadHelper.java
Allows ZECO terms to be loaded.
ZECO UI components added.
=> Ontology terms without ids (SCRUM-101)

src/main/cliapp/src/App.js, src/main/cliapp/src/components/Dashboard.js, src/main/cliapp/src/components/ontologies/CHEBIOntologyComponent.js, src/main/java/org/alliancegenome/curation_api/controllers/bulk/ontology/CHEBITermBulkController.java, src/main/java/org/alliancegenome/curation_api/controllers/crud/ontology/CHEBITermController.java, src/main/java/org/alliancegenome/curation_api/dao/CHEBITermDAO.java, src/main/java/org/alliancegenome/curation_api/dao/ontology/CHEBITermDAO.java, src/main/java/org/alliancegenome/curation_api/interfaces/bulk/ontology/CHEBITermBulkRESTInterface.java, src/main/java/org/alliancegenome/curation_api/interfaces/crud/ontology/CHEBITermRESTInterface.java, src/main/java/org/alliancegenome/curation_api/model/entities/ontology/CHEBITerm.java, src/main/java/org/alliancegenome/curation_api/services/ontology/CHEBITermService.java, src/test/java/org/alliancegenome/curation_api/crud/controllers/ontology/CHEBITermITCase.java
=> SCRUM-903: CHEBITerm CRUD

src/main/cliapp/src/components/DiseaseEditor.js, src/main/cliapp/src/components/datatables/DiseaseAnnotationsComponent.js
Autocomplete on name, curie, synonyms, cross-references, and secondary identifiers.  Show matching fields.
=> SCRUM-715 Add additional fields to disease autocomplete

src/main/cliapp/src/components/EvidenceEditor.js, src/main/cliapp/src/components/datatables/DiseaseAnnotationsComponent.js, src/main/cliapp/src/components/ontologies/ECOOntologyComponent.js, src/main/java/org/alliancegenome/curation_api/base/BaseOntologyTermService.java, src/main/java/org/alliancegenome/curation_api/controllers/bulk/ontology/EcoTermBulkController.java, src/main/java/org/alliancegenome/curation_api/controllers/crud/ontology/EcoTermController.java, src/main/java/org/alliancegenome/curation_api/dao/VocabularyDAO.java, src/main/java/org/alliancegenome/curation_api/interfaces/crud/ontology/EcoTermRESTInterface.java, src/main/java/org/alliancegenome/curation_api/model/entities/Vocabulary.java, src/main/java/org/alliancegenome/curation_api/model/entities/VocabularyTerm.java, src/main/java/org/alliancegenome/curation_api/model/entities/ontology/EcoTerm.java, src/main/java/org/alliancegenome/curation_api/services/VocabularyService.java, src/main/java/org/alliancegenome/curation_api/services/helpers/GenericOntologyLoadHelper.java, src/main/java/org/alliancegenome/curation_api/services/ontology/EcoTermService.java
Also includes loading of xrefs for ontologies (which fixes SCRUM-715), but not in strict accordance with the LinkML model as the required field 'page_areas' is not populated.
=> SCRUM-879 evidence code abbreviations mk2

src/main/cliapp/src/components/ControlledVocabularyComponent.js
Does exactly what it says on the tin!
=> Add abbreviation column to Terms table

src/main/java/org/alliancegenome/curation_api/model/entities/ontology/BooleanValueBridge.java, src/main/java/org/alliancegenome/curation_api/services/DiseaseAnnotationService.java, src/test/java/org/alliancegenome/curation_api/crud/controllers/DiseaseAnnotationITCase.java
Tested locally with Postman and UI
=> SCRUM-498: fix DiseaseAnnotation.negated updates

src/main/java/org/alliancegenome/curation_api/model/entities/Gene.java, src/main/java/org/alliancegenome/curation_api/services/GeneService.java
Can populate the new column using the following SQL query:
`UPDATE gene SET genetype_curie = type;`
=> SCRUM-1006 Link Genes to SOTerms

src/test/java/org/alliancegenome/curation_api/bulkupload/GeneBulkUploadITCase.java, src/test/resources/bulk/01_gene/00_mod_examples.json
Should have actually fixed them this time!
=> Fix gene tests attempt 2

src/main/java/org/alliancegenome/curation_api/interfaces/crud/AffectedGenomicModelCrudInterface.java, src/main/java/org/alliancegenome/curation_api/services/AffectedGenomicModelService.java, src/main/java/org/alliancegenome/curation_api/services/helpers/DtoConverterHelper.java, src/main/java/org/alliancegenome/curation_api/services/helpers/validators/AffectedGenomicModelValidator.java, src/test/java/org/alliancegenome/curation_api/bulkupload/AGMBulkUploadITCase.java, src/test/java/org/alliancegenome/curation_api/bulkupload/DiseaseAnnotationBulkUploadITCase.java, src/test/java/org/alliancegenome/curation_api/bulkupload/GeneBulkUploadITCase.java, src/test/java/org/alliancegenome/curation_api/crud/controllers/AffectedGenomicModelITCase.java, src/test/java/org/alliancegenome/curation_api/crud/controllers/DiseaseAnnotationITCase.java, src/test/resources/bulk/03_affected_genomic_model/00_mod_examples.json, src/test/resources/bulk/03_affected_genomic_model/01_all_fields.json, src/test/resources/bulk/03_affected_genomic_model/02_no_agm_components.json, src/test/resources/bulk/03_affected_genomic_model/03_no_agm_components_allele_id.json, src/test/resources/bulk/03_affected_genomic_model/04_no_agm_components_zygosity.json, src/test/resources/bulk/03_affected_genomic_model/05_no_cross_reference.json, src/test/resources/bulk/03_affected_genomic_model/06_no_cross_reference_id.json, src/test/resources/bulk/03_affected_genomic_model/07_no_cross_reference_pages.json, src/test/resources/bulk/03_affected_genomic_model/08_no_name.json, src/test/resources/bulk/03_affected_genomic_model/09_no_parental_population_ids.json, src/test/resources/bulk/03_affected_genomic_model/10_no_primary_id.json, src/test/resources/bulk/03_affected_genomic_model/11_no_secondary_ids.json, src/test/resources/bulk/03_affected_genomic_model/12_no_str_ids.json, src/test/resources/bulk/03_affected_genomic_model/13_no_subtype.json, src/test/resources/bulk/03_affected_genomic_model/14_no_synonyms.json, src/test/resources/bulk/03_affected_genomic_model/15_no_taxon_id.json, src/test/resources/bulk/03_affected_genomic_model/16_invalid_agm_components_allele_id.json, src/test/resources/bulk/03_affected_genomic_model/17_invalid_agm_components_allele_zygosity.json, src/test/resources/bulk/03_affected_genomic_model/18_invalid_str_id.json, src/test/resources/bulk/03_affected_genomic_model/19_invalid_subtype.json, src/test/resources/bulk/03_affected_genomic_model/20_invalid_taxon_id.json
Added synonyms and xrefs to AGM load.
CRUD and bulk validation code and tests written.
=> SCRUM-274 AGM loading, validation, and testing updates

src/main/cliapp/src/containers/genesPage/GenesTable.js
Not sure about how to test it with the new login...
=> SCRUM-1058: enable filter for Name in Genes Table

src/main/cliapp/src/containers/dataLoadsPage/NewBulkLoadForm.js, src/main/cliapp/src/service/DataLoadService.js, src/main/java/org/alliancegenome/curation_api/model/entities/bulkloads/BulkLoad.java, src/main/java/org/alliancegenome/curation_api/model/entities/bulkloads/BulkLoadFile.java
Add fileExtension to BulkLoad entity and select from dropdown in UI on creation of bulk load.
=> SCRUM-1067 mk2

src/main/cliapp/src/containers/experimentalConditionsPage/ExperimentalConditionsTable.js
Change from "Genes Table" to "Experimental Conditions Table"
=> SCRUM-1082 Fix table name
